// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXkJOcWLv_kVkmxNSpWdcwXt-GWIsGgug',
    appId: '1:480586147920:web:fa0a4da68df4baecaf4955',
    messagingSenderId: '480586147920',
    projectId: 'fincon-517fd',
    authDomain: 'fincon-517fd.firebaseapp.com',
    storageBucket: 'fincon-517fd.appspot.com',
    measurementId: 'G-426QPGT04R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2I5lA2Qnqd6KrpDYuHQu7Mm8oz-phncc',
    appId: '1:480586147920:android:a9a4d22e5f234f1eaf4955',
    messagingSenderId: '480586147920',
    projectId: 'fincon-517fd',
    storageBucket: 'fincon-517fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbZwFPHc1EVls52rEBRQim7GXGmGuo8Zc',
    appId: '1:480586147920:ios:e611dfd5227d37d1af4955',
    messagingSenderId: '480586147920',
    projectId: 'fincon-517fd',
    storageBucket: 'fincon-517fd.appspot.com',
    iosBundleId: 'com.example.finconApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbZwFPHc1EVls52rEBRQim7GXGmGuo8Zc',
    appId: '1:480586147920:ios:93ee3db085494e82af4955',
    messagingSenderId: '480586147920',
    projectId: 'fincon-517fd',
    storageBucket: 'fincon-517fd.appspot.com',
    iosBundleId: 'com.example.finconApp.RunnerTests',
  );
}
